/* eslint-disable */
// AUTO-GENERATED by scripts/build-question-bank.mjs. DO NOT EDIT BY HAND.
// generatedAt: 2026-04-20T17:15:09.919Z
import type { BinaryQuestion, QuadQuestion } from '@/lib/types/question';
export const BANK_BINARY: BinaryQuestion[] = [
  {
    "id": "law-b-0001",
    "format": "binary",
    "subject": "law",
    "topic": "登録業務範囲",
    "statement": "第3種旅行業者は、営業所のある市町村に隣接する市町村等の拠点区域内で実施する募集型企画旅行を催行することができる。",
    "answer": true,
    "explanation": "第3種旅行業者は、拠点区域内（営業所所在市町村および隣接市町村等）であれば、募集型企画旅行を実施できます。",
    "difficulty": 2,
    "sourceYear": 2022,
    "tags": [
      "登録",
      "第3種"
    ]
  },
  {
    "id": "law-b-0002",
    "format": "binary",
    "subject": "law",
    "topic": "営業保証金",
    "statement": "旅行業者は、営業保証金を主たる営業所の最寄りの供託所に供託しなければならない。",
    "answer": true,
    "explanation": "旅行業法第7条に定められた供託義務です。主たる営業所の最寄りの供託所に供託します。",
    "difficulty": 1,
    "tags": [
      "供託",
      "保証金"
    ]
  },
  {
    "id": "law-b-0003",
    "format": "binary",
    "subject": "law",
    "topic": "登録業務範囲",
    "statement": "地域限定旅行業者は、自らの営業所の所在する市町村およびこれに隣接する市町村に限って、募集型企画旅行を実施することができる。",
    "answer": true,
    "explanation": "地域限定旅行業者は、地域限定業務範囲内でのみ募集型企画旅行等を実施できます。",
    "difficulty": 2,
    "tags": [
      "地域限定"
    ]
  },
  {
    "id": "law-b-0004",
    "format": "binary",
    "subject": "law",
    "topic": "旅程管理主任者",
    "statement": "主任の国内旅程管理主任者は、国内の募集型企画旅行に同行し、旅行者に対して旅行サービスの確実な提供を確保しなければならない。",
    "answer": true,
    "explanation": "主任の旅程管理主任者は、旅程管理業務を統括し、旅行サービスの確実な提供を確保する責務を負います。",
    "difficulty": 2,
    "tags": [
      "旅程管理"
    ]
  },
  {
    "id": "law-b-0005",
    "format": "binary",
    "subject": "law",
    "topic": "旅行業務取扱管理者",
    "statement": "旅行業務取扱管理者は、営業所ごとに1名以上選任しなければならない。",
    "answer": true,
    "explanation": "旅行業法第11条の2により、営業所ごとに1名以上の選任が必要です。",
    "difficulty": 1,
    "tags": [
      "取扱管理者"
    ]
  },
  {
    "id": "law-b-0006",
    "format": "binary",
    "subject": "law",
    "topic": "取引条件説明書面",
    "statement": "旅行業者は、契約締結前に、旅行者に対して取引条件説明書面を交付しなければならないが、旅行者の同意があれば口頭で代えることができる。",
    "answer": false,
    "explanation": "旅行業法第12条の4により、書面交付は省略できません。電磁的方法による提供は同意があれば可能です。",
    "difficulty": 2,
    "tags": [
      "書面",
      "説明"
    ]
  },
  {
    "id": "law-b-0007",
    "format": "binary",
    "subject": "law",
    "topic": "契約書面",
    "statement": "旅行業者は、旅行契約の締結後、遅滞なく旅行者に契約書面を交付しなければならない。",
    "answer": true,
    "explanation": "旅行業法第12条の5により、契約締結後は遅滞なく契約書面を交付する義務があります。",
    "difficulty": 1,
    "tags": [
      "契約書面"
    ]
  },
  {
    "id": "law-b-0008",
    "format": "binary",
    "subject": "law",
    "topic": "営業保証金",
    "statement": "第1種旅行業者の営業保証金の額は7,000万円であり、第2種は1,100万円である。",
    "answer": true,
    "explanation": "登録種別ごとに基準額が決められています。第1種:7,000万円、第2種:1,100万円、第3種:300万円、地域限定:15万円。",
    "difficulty": 2,
    "tags": [
      "保証金"
    ]
  },
  {
    "id": "law-b-0009",
    "format": "binary",
    "subject": "law",
    "topic": "変更登録",
    "statement": "登録業務範囲を拡大するために変更登録を行う場合、変更登録手数料が必要である。",
    "answer": true,
    "explanation": "登録業務範囲の拡大を伴う変更登録には所定の手数料がかかります。",
    "difficulty": 2,
    "tags": [
      "変更登録"
    ]
  },
  {
    "id": "law-b-0010",
    "format": "binary",
    "subject": "law",
    "topic": "弁済業務保証金",
    "statement": "旅行業協会に加入している旅行業者（保証社員）は、営業保証金の供託に代えて弁済業務保証金分担金を納付する。",
    "answer": true,
    "explanation": "旅行業法第49条に基づき、保証社員は弁済業務保証金分担金の納付により営業保証金の供託が免除されます。",
    "difficulty": 2,
    "tags": [
      "弁済業務"
    ]
  },
  {
    "id": "law-b-0011",
    "format": "binary",
    "subject": "law",
    "topic": "広告規制",
    "statement": "旅行業者は、募集型企画旅行の広告において、旅行業務取扱管理者の氏名を表示する義務はない。",
    "answer": true,
    "explanation": "広告に氏名表示義務はありませんが、企画者名や料金、取消料等の表示義務はあります。",
    "difficulty": 2,
    "tags": [
      "広告"
    ]
  },
  {
    "id": "law-b-0012",
    "format": "binary",
    "subject": "law",
    "topic": "受注型企画旅行",
    "statement": "受注型企画旅行は、旅行者からの依頼により、旅行業者があらかじめ旅行計画を作成し、これを旅行者に提示して実施するものである。",
    "answer": true,
    "explanation": "旅行業法第2条の定義のとおり、受注型企画旅行は依頼に基づく企画旅行です。",
    "difficulty": 2,
    "tags": [
      "受注型"
    ]
  },
  {
    "id": "law-b-0013",
    "format": "binary",
    "subject": "law",
    "topic": "手配旅行",
    "statement": "手配旅行契約において、旅行業者は旅行サービスの提供自体を保証する責任を負う。",
    "answer": false,
    "explanation": "手配旅行では、旅行業者は手配の完成を目的とし、サービス提供そのものを保証するわけではありません。",
    "difficulty": 2,
    "tags": [
      "手配旅行"
    ]
  },
  {
    "id": "law-b-0014",
    "format": "binary",
    "subject": "law",
    "topic": "旅程管理",
    "statement": "旅程管理業務を行う者は、旅行の安全かつ円滑な実施を確保するため、出発前に旅行者への必要な説明等を行わなければならない。",
    "answer": true,
    "explanation": "旅程管理業務の具体的内容として、出発前の必要事項の説明が定められています。",
    "difficulty": 1,
    "tags": [
      "旅程管理"
    ]
  },
  {
    "id": "law-b-0015",
    "format": "binary",
    "subject": "law",
    "topic": "登録拒否事由",
    "statement": "旅行業登録を受けようとする者が破産者であって復権を得ない場合は、登録を拒否される。",
    "answer": true,
    "explanation": "旅行業法第6条の登録拒否事由に該当します。",
    "difficulty": 2,
    "tags": [
      "登録拒否"
    ]
  },
  {
    "id": "law-b-0016",
    "format": "binary",
    "subject": "law",
    "topic": "外務員",
    "statement": "外務員は、営業所以外で旅行業務を行う者をいい、外務員証を携帯しなければならない。",
    "answer": true,
    "explanation": "旅行業法第12条の6により、外務員証の携帯・呈示義務があります。",
    "difficulty": 2,
    "tags": [
      "外務員"
    ]
  },
  {
    "id": "law-b-0017",
    "format": "binary",
    "subject": "law",
    "topic": "取引条件説明書面",
    "statement": "電磁的方法による取引条件説明書面の提供は、旅行者の承諾がなくても旅行業者の判断で行うことができる。",
    "answer": false,
    "explanation": "電磁的方法による提供は、旅行者の同意が必要です。",
    "difficulty": 2,
    "tags": [
      "書面",
      "電磁的"
    ]
  },
  {
    "id": "law-b-0018",
    "format": "binary",
    "subject": "law",
    "topic": "旅行業協会",
    "statement": "旅行業協会は、旅行者と旅行業者との間で生じた取引に関する苦情の解決を図る業務を行う。",
    "answer": true,
    "explanation": "旅行業法第41条により、旅行業協会の業務の一つとして苦情解決が定められています。",
    "difficulty": 1,
    "tags": [
      "旅行業協会"
    ]
  },
  {
    "id": "law-b-0019",
    "format": "binary",
    "subject": "law",
    "topic": "旅程保証",
    "statement": "旅程保証は、手配旅行契約にも適用される。",
    "answer": false,
    "explanation": "旅程保証は募集型企画旅行契約および受注型企画旅行契約のみに適用されます。",
    "difficulty": 3,
    "tags": [
      "旅程保証"
    ]
  },
  {
    "id": "law-b-0020",
    "format": "binary",
    "subject": "law",
    "topic": "企画書面",
    "statement": "旅行業者は、受注型企画旅行契約に係る企画書面を作成した際、所定の費用を旅行者から収受することができる。",
    "answer": true,
    "explanation": "企画書面の作成に対して企画料金を収受できます。",
    "difficulty": 2,
    "tags": [
      "企画書面"
    ]
  },
  {
    "id": "practice-b-0001",
    "format": "binary",
    "subject": "practice",
    "topic": "JR運賃",
    "statement": "JRの普通運賃は、営業キロに応じて定められた賃率により計算される。",
    "answer": true,
    "explanation": "JR各社の普通運賃は営業キロに基づいた賃率表により算出します。",
    "difficulty": 1,
    "tags": [
      "JR",
      "運賃"
    ]
  },
  {
    "id": "practice-b-0002",
    "format": "binary",
    "subject": "practice",
    "topic": "JR乗車券",
    "statement": "乗車券の有効期間は、片道100kmを超える場合、100kmまでごとに1日が加算される。",
    "answer": true,
    "explanation": "JR乗車券の有効期間ルールのとおりです（片道）。",
    "difficulty": 2,
    "tags": [
      "JR",
      "乗車券"
    ]
  },
  {
    "id": "practice-b-0003",
    "format": "binary",
    "subject": "practice",
    "topic": "JR特急料金",
    "statement": "のぞみ号の特急料金は、のぞみ以外の新幹線特急料金に、のぞみ号特定特急料金を加算した額である。",
    "answer": true,
    "explanation": "のぞみは速達性に応じた特定の加算額が設定されています。",
    "difficulty": 2,
    "tags": [
      "JR",
      "新幹線"
    ]
  },
  {
    "id": "practice-b-0004",
    "format": "binary",
    "subject": "practice",
    "topic": "JR学生割引",
    "statement": "学生割引は、片道営業キロが100kmを超える場合に、普通運賃の2割引となる。",
    "answer": true,
    "explanation": "学生割引は片道101km以上で普通運賃2割引です。",
    "difficulty": 1,
    "tags": [
      "JR",
      "学割"
    ]
  },
  {
    "id": "practice-b-0005",
    "format": "binary",
    "subject": "practice",
    "topic": "JR往復割引",
    "statement": "往復割引は、片道の営業キロが600kmを超える区間で、往復運賃がそれぞれ1割引となる。",
    "answer": true,
    "explanation": "片道601km以上で往復運賃1割引が適用されます。",
    "difficulty": 2,
    "tags": [
      "JR",
      "往復"
    ]
  },
  {
    "id": "practice-b-0006",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（東北）",
    "statement": "白神山地は世界自然遺産に登録されている青森県と秋田県にまたがるブナ原生林地域である。",
    "answer": true,
    "explanation": "1993年に屋久島とともに日本初の世界自然遺産として登録されました。",
    "difficulty": 1,
    "tags": [
      "世界遺産",
      "東北"
    ]
  },
  {
    "id": "practice-b-0007",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（関東）",
    "statement": "草津温泉は群馬県にあり、自然湧出量が日本有数の規模を誇る温泉地である。",
    "answer": true,
    "explanation": "草津温泉は群馬県吾妻郡草津町にあり、湧出量は日本随一です。",
    "difficulty": 1,
    "tags": [
      "温泉",
      "群馬"
    ]
  },
  {
    "id": "practice-b-0008",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（中部）",
    "statement": "上高地は長野県松本市の槍ヶ岳・穂高岳を望む山岳景勝地で、中部山岳国立公園の一部である。",
    "answer": true,
    "explanation": "上高地は中部山岳国立公園に含まれる国の特別名勝・特別天然記念物です。",
    "difficulty": 1,
    "tags": [
      "国立公園",
      "長野"
    ]
  },
  {
    "id": "practice-b-0009",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（近畿）",
    "statement": "伊勢神宮の正宮は、内宮（皇大神宮）と外宮（豊受大神宮）の二つからなる。",
    "answer": true,
    "explanation": "伊勢神宮は内宮・外宮の両正宮を中心に125社で構成されます。",
    "difficulty": 1,
    "tags": [
      "神社",
      "三重"
    ]
  },
  {
    "id": "practice-b-0010",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（中国四国）",
    "statement": "厳島神社は広島県廿日市市にあり、海上に建つ朱塗りの大鳥居で知られる世界文化遺産である。",
    "answer": true,
    "explanation": "1996年に世界文化遺産に登録されました。",
    "difficulty": 1,
    "tags": [
      "世界遺産",
      "広島"
    ]
  },
  {
    "id": "practice-b-0011",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（九州沖縄）",
    "statement": "阿蘇山は長崎県に位置する世界最大級のカルデラを持つ活火山である。",
    "answer": false,
    "explanation": "阿蘇山は熊本県にあります。",
    "difficulty": 2,
    "tags": [
      "火山",
      "九州"
    ]
  },
  {
    "id": "practice-b-0012",
    "format": "binary",
    "subject": "practice",
    "topic": "JR運賃",
    "statement": "大人の運賃を1として、小児（6歳以上12歳未満）の運賃は0.5（半額）で計算する。",
    "answer": true,
    "explanation": "JRの小児運賃は大人の半額で、10円未満の端数は切り捨てます。",
    "difficulty": 1,
    "tags": [
      "JR",
      "小児"
    ]
  },
  {
    "id": "practice-b-0013",
    "format": "binary",
    "subject": "practice",
    "topic": "JR乗車券",
    "statement": "連続乗車券は、片道乗車券を発売できない区間が含まれる場合に発売する。",
    "answer": true,
    "explanation": "一筆書き不可の経路のため、2枚組の連続乗車券で発売されます。",
    "difficulty": 3,
    "tags": [
      "JR",
      "連続"
    ]
  },
  {
    "id": "practice-b-0014",
    "format": "binary",
    "subject": "practice",
    "topic": "宿泊",
    "statement": "旅館業法における旅館・ホテル営業は、施設ごとに都道府県知事等の許可が必要である。",
    "answer": true,
    "explanation": "旅館業法第3条により、営業にあたり都道府県知事等の許可が必要です。",
    "difficulty": 2,
    "tags": [
      "旅館業法"
    ]
  },
  {
    "id": "practice-b-0015",
    "format": "binary",
    "subject": "practice",
    "topic": "国内観光地理",
    "statement": "松島（宮城県）、天橋立（京都府）、宮島（広島県）は日本三景と呼ばれる。",
    "answer": true,
    "explanation": "日本三景は松島・天橋立・宮島の3ヶ所です。",
    "difficulty": 1,
    "tags": [
      "三景"
    ]
  },
  {
    "id": "practice-b-0016",
    "format": "binary",
    "subject": "practice",
    "topic": "JR特急料金",
    "statement": "指定席特急料金に対して、自由席特急料金は通常530円引きである。",
    "answer": true,
    "explanation": "自由席は指定席より通常530円安い料金設定です（2024年時点の基準）。",
    "difficulty": 2,
    "tags": [
      "JR",
      "自由席"
    ]
  },
  {
    "id": "practice-b-0017",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（北海道）",
    "statement": "知床半島は、北海道の東部に位置し、ヒグマやエゾシカの生息地として知られる世界自然遺産である。",
    "answer": true,
    "explanation": "2005年に世界自然遺産に登録されました。",
    "difficulty": 1,
    "tags": [
      "世界遺産",
      "北海道"
    ]
  },
  {
    "id": "practice-b-0018",
    "format": "binary",
    "subject": "practice",
    "topic": "JR乗車券",
    "statement": "大都市近郊区間内相互発着の乗車券は、どの経路で乗車しても最短経路の運賃で発売される。",
    "answer": true,
    "explanation": "大都市近郊区間内は経路選択乗車が可能です。",
    "difficulty": 2,
    "tags": [
      "JR",
      "近郊"
    ]
  },
  {
    "id": "practice-b-0019",
    "format": "binary",
    "subject": "practice",
    "topic": "観光資源（関東）",
    "statement": "日光の社寺（栃木県）は、世界文化遺産として東照宮・二荒山神社・輪王寺の建造物が登録されている。",
    "answer": true,
    "explanation": "1999年に世界文化遺産に登録されました。",
    "difficulty": 1,
    "tags": [
      "世界遺産",
      "栃木"
    ]
  },
  {
    "id": "practice-b-0020",
    "format": "binary",
    "subject": "practice",
    "topic": "JR運賃",
    "statement": "幹線と地方交通線をまたがって乗車する場合、運賃は換算キロ（または擬制キロ）を用いて幹線の賃率で計算する。",
    "answer": true,
    "explanation": "地方交通線の営業キロを換算キロに直し、幹線賃率で算出する方式です。",
    "difficulty": 3,
    "tags": [
      "JR",
      "賃率"
    ]
  },
  {
    "id": "sample-json-b-0001",
    "format": "binary",
    "subject": "law",
    "topic": "取扱管理者の選任",
    "statement": "旅行業者は、営業所ごとに旅行業務取扱管理者を2名以上選任しなければならない。",
    "answer": false,
    "explanation": "旅行業法第11条の2により必要なのは1名以上です。2名以上ではありません。",
    "difficulty": 1,
    "tags": [
      "取扱管理者",
      "選任"
    ]
  },
  {
    "id": "terms-b-0001",
    "format": "binary",
    "subject": "terms",
    "topic": "募集型企画旅行契約",
    "statement": "募集型企画旅行契約において、契約締結後に旅行者が契約を解除する場合、いかなる場合も取消料は発生しない。",
    "answer": false,
    "explanation": "旅行開始日から起算して定められた日数内に解除する場合、区分ごとに定められた取消料が発生します。",
    "difficulty": 1,
    "tags": [
      "取消料"
    ]
  },
  {
    "id": "terms-b-0002",
    "format": "binary",
    "subject": "terms",
    "topic": "特別補償",
    "statement": "特別補償規程に基づく見舞金の支払は、旅行業者の故意または過失の有無にかかわらず行われる。",
    "answer": true,
    "explanation": "特別補償は旅行業者の責任の有無を問わず、一定の事故に対して支払われる制度です。",
    "difficulty": 2,
    "tags": [
      "特別補償"
    ]
  },
  {
    "id": "terms-b-0003",
    "format": "binary",
    "subject": "terms",
    "topic": "旅程保証",
    "statement": "旅程保証は、旅行業者の責に帰すべき事由の有無にかかわらず、契約内容の重要な変更が生じた場合に変更補償金を支払うものである。",
    "answer": true,
    "explanation": "旅程保証は無過失責任的に、重要な変更に対して所定の変更補償金を支払います。",
    "difficulty": 2,
    "tags": [
      "旅程保証"
    ]
  },
  {
    "id": "terms-b-0004",
    "format": "binary",
    "subject": "terms",
    "topic": "受注型企画旅行契約",
    "statement": "受注型企画旅行契約の締結にあたっては、企画料金を契約書面に明示しなければならない。",
    "answer": true,
    "explanation": "企画料金は契約書面への記載事項です。",
    "difficulty": 2,
    "tags": [
      "受注型",
      "企画料金"
    ]
  },
  {
    "id": "terms-b-0005",
    "format": "binary",
    "subject": "terms",
    "topic": "取消料",
    "statement": "貸切バスによる国内旅行の取消料率は、募集型企画旅行と受注型企画旅行で異なる。",
    "answer": true,
    "explanation": "貸切輸送に係る取消料率は契約類型ごとに定められており、両者は異なります。",
    "difficulty": 3,
    "tags": [
      "取消料",
      "貸切"
    ]
  },
  {
    "id": "terms-b-0006",
    "format": "binary",
    "subject": "terms",
    "topic": "取消料",
    "statement": "旅行開始日の前日に旅行者の都合で募集型企画旅行契約を解除する場合、旅行代金の40%以内の取消料を請求できる。",
    "answer": true,
    "explanation": "前日の取消は40%が上限です（日帰り旅行は別規定あり）。",
    "difficulty": 1,
    "tags": [
      "取消料"
    ]
  },
  {
    "id": "terms-b-0007",
    "format": "binary",
    "subject": "terms",
    "topic": "旅行開始後の解除",
    "statement": "旅行者の責に帰すべき事由により旅行開始後に契約を解除する場合、旅行業者は未提供部分の料金を払い戻さない。",
    "answer": false,
    "explanation": "既提供部分の料金は請求できますが、未提供部分の料金から解除手続費用等を除いた金額は払い戻します。",
    "difficulty": 2,
    "tags": [
      "解除"
    ]
  },
  {
    "id": "terms-b-0008",
    "format": "binary",
    "subject": "terms",
    "topic": "宿泊約款",
    "statement": "宿泊約款において、宿泊施設側は正当な理由があれば宿泊契約の締結を拒むことができる。",
    "answer": true,
    "explanation": "モデル宿泊約款第5条に定める契約締結拒否事由があります。",
    "difficulty": 1,
    "tags": [
      "宿泊約款"
    ]
  },
  {
    "id": "terms-b-0009",
    "format": "binary",
    "subject": "terms",
    "topic": "旅程管理",
    "statement": "旅程管理業務を行う者は、旅行中に旅行者に対して契約内容を変更するための措置を迅速に講じなければならない。",
    "answer": true,
    "explanation": "変更措置は旅程管理業務の中心的内容の一つです。",
    "difficulty": 2,
    "tags": [
      "旅程管理"
    ]
  },
  {
    "id": "terms-b-0010",
    "format": "binary",
    "subject": "terms",
    "topic": "手配旅行契約",
    "statement": "手配旅行契約において、旅行業者の手配が完了したときは、旅行サービスが提供されなくても旅行業者の義務は履行されたものとする。",
    "answer": true,
    "explanation": "手配完成債務として、手配完了で旅行業者の義務は履行されたと扱われます。",
    "difficulty": 2,
    "tags": [
      "手配旅行"
    ]
  },
  {
    "id": "terms-b-0011",
    "format": "binary",
    "subject": "terms",
    "topic": "旅行業者の責任",
    "statement": "旅行業者は、旅程保証の対象となる変更であっても、旅行者の損害を賠償する責任を負うことがある。",
    "answer": true,
    "explanation": "旅行業者に故意・過失がある場合は損害賠償責任を負います。",
    "difficulty": 3,
    "tags": [
      "損害賠償"
    ]
  },
  {
    "id": "terms-b-0012",
    "format": "binary",
    "subject": "terms",
    "topic": "募集型企画旅行契約",
    "statement": "旅行業者は、契約締結前に旅行者に対し、契約内容及び取引条件について説明した書面を交付しなければならない。",
    "answer": true,
    "explanation": "契約締結前の取引条件説明書面の交付義務があります。",
    "difficulty": 1,
    "tags": [
      "書面"
    ]
  },
  {
    "id": "terms-b-0013",
    "format": "binary",
    "subject": "terms",
    "topic": "旅行代金",
    "statement": "旅行代金は、契約書面に定められた期日までに旅行者が支払わなければ、旅行業者は契約を解除することができる。",
    "answer": true,
    "explanation": "旅行代金の不払いは旅行業者による契約解除事由となります。",
    "difficulty": 2,
    "tags": [
      "旅行代金"
    ]
  },
  {
    "id": "terms-b-0014",
    "format": "binary",
    "subject": "terms",
    "topic": "取消料",
    "statement": "旅行開始日の30日前までに旅行者の都合で解除する場合、取消料は発生しない。",
    "answer": false,
    "explanation": "募集型企画旅行では、日帰り11日前／泊付き21日前からの解除で取消料が発生します（2024年改定運用）。",
    "difficulty": 2,
    "tags": [
      "取消料"
    ]
  },
  {
    "id": "terms-b-0015",
    "format": "binary",
    "subject": "terms",
    "topic": "特別補償",
    "statement": "特別補償に基づく死亡補償金は、国内旅行で1,500万円と定められている。",
    "answer": true,
    "explanation": "国内旅行における死亡補償金は1,500万円です。",
    "difficulty": 2,
    "tags": [
      "特別補償",
      "補償金"
    ]
  },
  {
    "id": "terms-b-0016",
    "format": "binary",
    "subject": "terms",
    "topic": "旅程保証",
    "statement": "列車やバス等の等級・設備が契約内容より低いものに変更された場合、変更補償金の支払対象となる。",
    "answer": true,
    "explanation": "契約内容を構成する重要な項目の変更として、変更補償金の対象です。",
    "difficulty": 3,
    "tags": [
      "旅程保証"
    ]
  },
  {
    "id": "terms-b-0017",
    "format": "binary",
    "subject": "terms",
    "topic": "手配旅行契約",
    "statement": "手配旅行契約において、旅行業者は所定の旅行業務取扱料金を収受できる。",
    "answer": true,
    "explanation": "手配旅行には取扱料金が定められており、旅行者から収受できます。",
    "difficulty": 1,
    "tags": [
      "手配旅行"
    ]
  },
  {
    "id": "terms-b-0018",
    "format": "binary",
    "subject": "terms",
    "topic": "契約書面",
    "statement": "契約書面の交付を電磁的方法で行う場合、旅行者の承諾を得る必要がある。",
    "answer": true,
    "explanation": "電磁的方法による交付は承諾を要します。",
    "difficulty": 2,
    "tags": [
      "契約書面"
    ]
  },
  {
    "id": "terms-b-0019",
    "format": "binary",
    "subject": "terms",
    "topic": "契約解除",
    "statement": "天災地変等により旅行の安全かつ円滑な実施が不可能となった場合、旅行業者は旅行開始後であっても契約を解除することができる。",
    "answer": true,
    "explanation": "約款上、やむを得ない事由による解除が認められています。",
    "difficulty": 2,
    "tags": [
      "解除"
    ]
  },
  {
    "id": "terms-b-0020",
    "format": "binary",
    "subject": "terms",
    "topic": "取消料",
    "statement": "旅行開始日の前々日に旅行者の都合で解除する場合、取消料は旅行代金の30%を上限とする。",
    "answer": false,
    "explanation": "前々日の取消料は20%が上限です（前日40%、当日50%、開始後100%）。",
    "difficulty": 2,
    "tags": [
      "取消料"
    ]
  }
];

export const BANK_QUAD: QuadQuestion[] = [
  {
    "id": "law-q-0001",
    "format": "quad",
    "subject": "law",
    "topic": "営業保証金",
    "prompt": "第1種旅行業者の営業保証金の基準額として、旅行業法施行規則で定められている額は次のうちどれか。",
    "choices": [
      "1,100万円",
      "3,000万円",
      "5,000万円",
      "7,000万円"
    ],
    "answerIndex": 3,
    "explanation": "第1種の基準額は7,000万円。前事業年度の年間取扱額により加算されます。",
    "difficulty": 2,
    "tags": [
      "保証金"
    ]
  },
  {
    "id": "law-q-0002",
    "format": "quad",
    "subject": "law",
    "topic": "旅程管理主任者",
    "prompt": "旅程管理主任者の資格を得るための要件として誤っているものは次のうちどれか。",
    "choices": [
      "観光庁長官の登録を受けた研修の修了",
      "旅程管理業務に関する実務経験の実施",
      "観光庁長官が認定する資格試験の合格",
      "旅行業務取扱管理者の資格の保有"
    ],
    "answerIndex": 3,
    "explanation": "旅行業務取扱管理者資格は旅程管理主任者の要件ではありません。必要なのは研修修了と実務経験です。",
    "difficulty": 3,
    "tags": [
      "旅程管理"
    ]
  },
  {
    "id": "law-q-0003",
    "format": "quad",
    "subject": "law",
    "topic": "登録拒否事由",
    "prompt": "旅行業登録の拒否事由に該当しないものは次のうちどれか。",
    "choices": [
      "成年被後見人または被保佐人",
      "破産手続開始の決定を受けて復権を得ない者",
      "旅行業法違反で登録取消後5年を経過しない者",
      "旅行業務取扱管理者の資格を有しない者"
    ],
    "answerIndex": 3,
    "explanation": "取扱管理者の資格未保有自体は登録拒否事由ではありません（営業所ごとの選任義務とは別論点）。",
    "difficulty": 3,
    "tags": [
      "登録拒否"
    ]
  },
  {
    "id": "law-q-0004",
    "format": "quad",
    "subject": "law",
    "topic": "取引条件説明書面",
    "prompt": "取引条件説明書面の記載事項として、誤っているものは次のうちどれか。",
    "choices": [
      "企画者の氏名または名称",
      "旅行代金およびその支払時期",
      "取消料に関する事項",
      "旅程管理主任者の氏名"
    ],
    "answerIndex": 3,
    "explanation": "旅程管理主任者氏名は取引条件説明書面の記載事項ではありません。",
    "difficulty": 2,
    "tags": [
      "書面",
      "記載事項"
    ]
  },
  {
    "id": "law-q-0005",
    "format": "quad",
    "subject": "law",
    "topic": "外務員",
    "prompt": "旅行業法における外務員について正しいものは次のうちどれか。",
    "choices": [
      "外務員は営業所内においてのみ旅行業務を行う",
      "外務員証の携帯は不要である",
      "外務員の行為は所属する旅行業者の行為とみなされる",
      "外務員は旅行業務取扱管理者の指示を受ける必要がない"
    ],
    "answerIndex": 2,
    "explanation": "外務員の行為は所属旅行業者の行為とみなされるのが原則です。",
    "difficulty": 2,
    "tags": [
      "外務員"
    ]
  },
  {
    "id": "law-q-0006",
    "format": "quad",
    "subject": "law",
    "topic": "企画旅行",
    "prompt": "次のうち、旅行業法上の「募集型企画旅行」の定義に最も合致するものはどれか。",
    "choices": [
      "旅行者の依頼により旅行計画を作成し実施する旅行",
      "旅行業者があらかじめ旅行計画を作成し参加者を募集して実施する旅行",
      "旅行者の依頼に基づき運送・宿泊の手配のみを行う旅行",
      "旅行業者が他の旅行業者に取次ぐ旅行"
    ],
    "answerIndex": 1,
    "explanation": "募集型企画旅行は、旅行業者が企画し参加者を広く募集して実施する旅行です。",
    "difficulty": 1,
    "tags": [
      "募集型"
    ]
  },
  {
    "id": "law-q-0007",
    "format": "quad",
    "subject": "law",
    "topic": "旅行業協会",
    "prompt": "旅行業協会の業務として規定されていないものは次のうちどれか。",
    "choices": [
      "苦情の解決に関する業務",
      "弁済業務保証金の供託および弁済業務",
      "旅行業務取扱管理者試験の実施",
      "旅行業務に関する研修"
    ],
    "answerIndex": 2,
    "explanation": "取扱管理者試験の実施は観光庁長官が指定する試験機関が担当します。協会の業務ではありません。",
    "difficulty": 3,
    "tags": [
      "旅行業協会"
    ]
  },
  {
    "id": "law-q-0008",
    "format": "quad",
    "subject": "law",
    "topic": "登録業務範囲",
    "prompt": "地域限定旅行業者が実施できる業務として正しいものは次のうちどれか。",
    "choices": [
      "営業所の所在する市町村および隣接する市町村等の拠点区域内で完結する募集型企画旅行",
      "全国を目的地とする募集型企画旅行",
      "海外を目的地とする募集型企画旅行",
      "拠点区域外での手配旅行"
    ],
    "answerIndex": 0,
    "explanation": "地域限定は拠点区域内で完結する企画旅行等に限定されます。",
    "difficulty": 2,
    "tags": [
      "地域限定"
    ]
  },
  {
    "id": "law-q-0009",
    "format": "quad",
    "subject": "law",
    "topic": "営業保証金",
    "prompt": "営業保証金の還付を請求できる者について正しいものは次のうちどれか。",
    "choices": [
      "旅行者と旅行業者との間の旅行業務に関する取引で生じた債権の債権者",
      "旅行業者の従業員の給与債権者",
      "旅行業者と取引のある運送業者の一般債権者",
      "旅行業者の税金滞納に係る国税債権者"
    ],
    "answerIndex": 0,
    "explanation": "旅行業務に関する取引で生じた債権者に限り還付を受けられます。",
    "difficulty": 2,
    "tags": [
      "保証金",
      "還付"
    ]
  },
  {
    "id": "law-q-0010",
    "format": "quad",
    "subject": "law",
    "topic": "取扱管理者",
    "prompt": "旅行業務取扱管理者の職務として誤っているものは次のうちどれか。",
    "choices": [
      "取引条件の説明に関する事項",
      "契約書面等に関する事項",
      "苦情の処理に関する事項",
      "営業保証金の供託に関する事項"
    ],
    "answerIndex": 3,
    "explanation": "営業保証金の供託は旅行業者の義務であり、取扱管理者の職務として法定されていません。",
    "difficulty": 2,
    "tags": [
      "取扱管理者"
    ]
  },
  {
    "id": "practice-q-0001",
    "format": "quad",
    "subject": "practice",
    "topic": "JR運賃",
    "prompt": "JRの普通乗車券について、小児運賃の計算方法として正しいものはどれか。",
    "choices": [
      "大人運賃を1として0.5を乗じ、10円未満を切り上げる",
      "大人運賃を1として0.5を乗じ、10円未満を切り捨てる",
      "大人運賃を1として0.5を乗じ、端数はそのまま表示する",
      "大人運賃を1として0.6を乗じ、10円未満を切り捨てる"
    ],
    "answerIndex": 1,
    "explanation": "小児運賃は大人運賃の半額（×0.5）で10円未満切り捨てが原則です。",
    "difficulty": 2,
    "tags": [
      "JR",
      "小児"
    ]
  },
  {
    "id": "practice-q-0002",
    "format": "quad",
    "subject": "practice",
    "topic": "JR乗車券",
    "prompt": "片道営業キロが400kmの乗車券の有効期間は、次のうちどれか。",
    "choices": [
      "2日",
      "3日",
      "4日",
      "5日"
    ],
    "answerIndex": 1,
    "explanation": "101km〜200kmで2日、それを超えると100kmごとに1日加算。400kmなら3日。",
    "difficulty": 2,
    "tags": [
      "JR",
      "有効期間"
    ]
  },
  {
    "id": "practice-q-0003",
    "format": "quad",
    "subject": "practice",
    "topic": "JR特急料金",
    "prompt": "東海道新幹線「のぞみ」の特急料金は、同一区間の「ひかり・こだま」の料金に加算される金額を何というか。",
    "choices": [
      "のぞみ号加算料金",
      "のぞみ特定特急料金",
      "のぞみ号特定特急料金",
      "特別車両料金"
    ],
    "answerIndex": 2,
    "explanation": "「のぞみ号特定特急料金」として加算されます。",
    "difficulty": 3,
    "tags": [
      "JR",
      "新幹線"
    ]
  },
  {
    "id": "practice-q-0004",
    "format": "quad",
    "subject": "practice",
    "topic": "JR学割",
    "prompt": "JRの学生割引について正しいものはどれか。",
    "choices": [
      "片道50km以上で1割引",
      "片道100kmを超える場合に2割引",
      "片道200km以上で3割引",
      "片道300km以上で5割引"
    ],
    "answerIndex": 1,
    "explanation": "学割は101km以上の普通運賃について2割引です。",
    "difficulty": 1,
    "tags": [
      "JR",
      "学割"
    ]
  },
  {
    "id": "practice-q-0005",
    "format": "quad",
    "subject": "practice",
    "topic": "観光資源",
    "prompt": "次のうち、世界文化遺産に登録されている日本の物件はどれか。",
    "choices": [
      "屋久島",
      "白神山地",
      "厳島神社",
      "知床"
    ],
    "answerIndex": 2,
    "explanation": "屋久島・白神山地・知床は世界自然遺産。厳島神社は世界文化遺産です。",
    "difficulty": 2,
    "tags": [
      "世界遺産"
    ]
  },
  {
    "id": "practice-q-0006",
    "format": "quad",
    "subject": "practice",
    "topic": "観光資源",
    "prompt": "次の温泉地と所在県の組合せのうち、正しいものはどれか。",
    "choices": [
      "有馬温泉 — 和歌山県",
      "道後温泉 — 高知県",
      "草津温泉 — 群馬県",
      "別府温泉 — 熊本県"
    ],
    "answerIndex": 2,
    "explanation": "有馬は兵庫県、道後は愛媛県、別府は大分県。草津は群馬県。",
    "difficulty": 2,
    "tags": [
      "温泉"
    ]
  },
  {
    "id": "practice-q-0007",
    "format": "quad",
    "subject": "practice",
    "topic": "観光資源",
    "prompt": "次のうち、国立公園に指定されていないものはどれか。",
    "choices": [
      "日光国立公園",
      "富士箱根伊豆国立公園",
      "松島国立公園",
      "阿蘇くじゅう国立公園"
    ],
    "answerIndex": 2,
    "explanation": "松島は「松島県立自然公園」ですが、国立公園ではありません。",
    "difficulty": 3,
    "tags": [
      "国立公園"
    ]
  },
  {
    "id": "practice-q-0008",
    "format": "quad",
    "subject": "practice",
    "topic": "観光資源",
    "prompt": "次の郷土料理と都道府県の組合せのうち、誤っているものはどれか。",
    "choices": [
      "いちご煮 — 青森県",
      "きりたんぽ — 秋田県",
      "ほうとう — 長野県",
      "ちゃんぽん — 長崎県"
    ],
    "answerIndex": 2,
    "explanation": "ほうとうは山梨県の郷土料理です。",
    "difficulty": 2,
    "tags": [
      "郷土料理"
    ]
  },
  {
    "id": "practice-q-0009",
    "format": "quad",
    "subject": "practice",
    "topic": "観光資源",
    "prompt": "次の祭りと開催地の組合せのうち、正しいものはどれか。",
    "choices": [
      "ねぶた祭 — 青森県青森市",
      "竿燈まつり — 山形県山形市",
      "七夕まつり — 宮城県仙台市でのみ全国的知名度",
      "よさこい祭り — 愛媛県松山市"
    ],
    "answerIndex": 0,
    "explanation": "竿燈は秋田市、七夕も仙台市で正しいが「のみ」は言い過ぎ、よさこいは高知市。ねぶたは青森市が正解。",
    "difficulty": 2,
    "tags": [
      "祭り"
    ]
  },
  {
    "id": "practice-q-0010",
    "format": "quad",
    "subject": "practice",
    "topic": "JR運賃",
    "prompt": "JRの往復割引乗車券の適用条件として正しいものはどれか。",
    "choices": [
      "片道400km以上",
      "片道500kmを超える",
      "片道600kmを超える",
      "片道1000km以上"
    ],
    "answerIndex": 2,
    "explanation": "片道601km以上の区間で往復運賃それぞれ1割引になります。",
    "difficulty": 2,
    "tags": [
      "JR",
      "往復"
    ]
  },
  {
    "id": "sample-json-q-0001",
    "format": "quad",
    "subject": "practice",
    "topic": "日本三景",
    "prompt": "次のうち、日本三景に含まれないものはどれか。",
    "choices": [
      "松島",
      "天橋立",
      "宮島",
      "石見銀山"
    ],
    "answerIndex": 3,
    "explanation": "日本三景は松島・天橋立・宮島。石見銀山は世界文化遺産ですが三景ではありません。",
    "difficulty": 1,
    "tags": [
      "三景"
    ]
  },
  {
    "id": "terms-q-0001",
    "format": "quad",
    "subject": "terms",
    "topic": "取消料",
    "prompt": "旅行開始日が9月20日の宿泊付き国内募集型企画旅行について、9月10日に旅行者の都合で解除した場合の取消料率として正しいものはどれか。",
    "choices": [
      "取消料はかからない",
      "旅行代金の20%以内",
      "旅行代金の30%以内",
      "旅行代金の40%以内"
    ],
    "answerIndex": 1,
    "explanation": "宿泊付きは21日前〜8日前で20%以内。9月20日の10日前（9月10日）は20%です。",
    "difficulty": 2,
    "tags": [
      "取消料"
    ]
  },
  {
    "id": "terms-q-0002",
    "format": "quad",
    "subject": "terms",
    "topic": "特別補償",
    "prompt": "特別補償規程における補償金のうち、国内旅行の入院見舞金の支給対象となるのはどれか。",
    "choices": [
      "入院日数1日以上",
      "入院日数3日以上",
      "入院日数7日以上",
      "入院日数14日以上"
    ],
    "answerIndex": 1,
    "explanation": "入院見舞金は入院日数3日以上が対象（国内旅行）。",
    "difficulty": 3,
    "tags": [
      "特別補償"
    ]
  },
  {
    "id": "terms-q-0003",
    "format": "quad",
    "subject": "terms",
    "topic": "旅程保証",
    "prompt": "変更補償金の支払対象となる契約内容の重要な変更に該当するものはどれか。",
    "choices": [
      "ホテルの室タイプの変更（等級は同等）",
      "運送機関の等級・設備の低下",
      "目的地での食事の献立変更",
      "旅行案内人の変更"
    ],
    "answerIndex": 1,
    "explanation": "運送機関の等級・設備の低下は旅程保証の対象です。",
    "difficulty": 2,
    "tags": [
      "旅程保証"
    ]
  },
  {
    "id": "terms-q-0004",
    "format": "quad",
    "subject": "terms",
    "topic": "受注型企画旅行",
    "prompt": "受注型企画旅行契約の企画料金について正しいものはどれか。",
    "choices": [
      "旅行代金に含まれるため別途明示する必要はない",
      "取引条件説明書面にのみ記載すればよい",
      "企画書面に明示し、旅行者から収受できる",
      "企画書面への記載は任意であり収受はできない"
    ],
    "answerIndex": 2,
    "explanation": "企画書面に企画料金を明示し、これを旅行者から収受することが認められます。",
    "difficulty": 2,
    "tags": [
      "受注型"
    ]
  },
  {
    "id": "terms-q-0005",
    "format": "quad",
    "subject": "terms",
    "topic": "旅行開始後の解除",
    "prompt": "旅行開始後に旅行者の都合で契約を一部解除した場合の取り扱いとして、正しいものはどれか。",
    "choices": [
      "未提供部分の料金は全額返金される",
      "解除手続費用等を差し引いた額が払い戻される",
      "一切返金されない",
      "旅行者の書面請求があれば全額返金される"
    ],
    "answerIndex": 1,
    "explanation": "既提供分は請求可、未提供分は解除手続費用等を差し引いて払い戻します。",
    "difficulty": 2,
    "tags": [
      "解除"
    ]
  },
  {
    "id": "terms-q-0006",
    "format": "quad",
    "subject": "terms",
    "topic": "宿泊約款",
    "prompt": "モデル宿泊約款において、宿泊施設が契約締結を拒むことができる事由に該当しないものはどれか。",
    "choices": [
      "申込が宿泊約款によらない場合",
      "施設に余裕がない場合",
      "宿泊客が公序良俗に反する行為をするおそれがあるとき",
      "宿泊客が宿泊施設から遠方に住んでいる場合"
    ],
    "answerIndex": 3,
    "explanation": "居住地の遠近は契約締結拒否事由ではありません。",
    "difficulty": 2,
    "tags": [
      "宿泊約款"
    ]
  },
  {
    "id": "terms-q-0007",
    "format": "quad",
    "subject": "terms",
    "topic": "取消料",
    "prompt": "日帰り国内募集型企画旅行について、旅行開始日の前日に旅行者の都合で解除した場合の取消料率として正しいものはどれか。",
    "choices": [
      "旅行代金の20%以内",
      "旅行代金の30%以内",
      "旅行代金の40%以内",
      "旅行代金の50%以内"
    ],
    "answerIndex": 2,
    "explanation": "日帰り前日の取消料は40%以内が上限です。",
    "difficulty": 2,
    "tags": [
      "取消料",
      "日帰り"
    ]
  },
  {
    "id": "terms-q-0008",
    "format": "quad",
    "subject": "terms",
    "topic": "特別補償",
    "prompt": "特別補償における国内旅行の死亡補償金として正しい金額は次のうちどれか。",
    "choices": [
      "500万円",
      "1,000万円",
      "1,500万円",
      "2,500万円"
    ],
    "answerIndex": 2,
    "explanation": "国内旅行における死亡補償金は1,500万円です。",
    "difficulty": 2,
    "tags": [
      "特別補償",
      "補償金"
    ]
  },
  {
    "id": "terms-q-0009",
    "format": "quad",
    "subject": "terms",
    "topic": "旅程保証",
    "prompt": "旅程保証における変更補償金の支払は、旅行代金に対して定められた率によって算定される。次のうち、旅程保証の対象外となるのはどれか。",
    "choices": [
      "宿泊機関の種類または名称の変更",
      "運送機関の種類または会社名の変更",
      "旅行中の観光地における食事メニューの変更",
      "旅行日程の変更（旅行開始日または終了日の変更）"
    ],
    "answerIndex": 2,
    "explanation": "食事メニューの変更は旅程保証の対象ではありません。",
    "difficulty": 3,
    "tags": [
      "旅程保証"
    ]
  },
  {
    "id": "terms-q-0010",
    "format": "quad",
    "subject": "terms",
    "topic": "旅行代金",
    "prompt": "旅行代金の変更について正しいものはどれか。",
    "choices": [
      "旅行業者の判断でいつでも変更できる",
      "運送機関の運賃・料金の改定等により、契約書面で定めた場合に限り変更できる",
      "契約締結後は一切変更できない",
      "旅行者の同意があれば無条件で変更できる"
    ],
    "answerIndex": 1,
    "explanation": "運賃料金の改定等の特定事由かつ契約書面の記載がある場合に限り、代金の変更が可能です。",
    "difficulty": 2,
    "tags": [
      "旅行代金"
    ]
  }
];

export const BANK_META = {
  "generatedAt": "2026-04-20T17:15:09.919Z",
  "counts": {
    "binary": 61,
    "quad": 31
  },
  "bySubject": {
    "law": {
      "binary": 21,
      "quad": 10
    },
    "terms": {
      "binary": 20,
      "quad": 10
    },
    "practice": {
      "binary": 20,
      "quad": 11
    }
  },
  "sourceFiles": [
    "content/questions/sample.json",
    "content/questions/seed-binary-law.csv",
    "content/questions/seed-binary-practice.csv",
    "content/questions/seed-binary-terms.csv",
    "content/questions/seed-quad-law.csv",
    "content/questions/seed-quad-practice.csv",
    "content/questions/seed-quad-terms.csv"
  ]
} as const;
